name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo run
    - name: Run
      run: cargo run
    - name: Update
      run: bash ./src/builder.sh
